# Generated by Django 5.1 on 2024-09-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cafeteria', models.CharField(max_length=250)),
                ('local', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=250)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empregado', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=250)),
                ('salario', models.PositiveBigIntegerField()),
                ('id_cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_compra', models.DateTimeField(max_length=250)),
                ('id_cafeteria_empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cafeteria')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empregado')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cafeteria')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
    ]
